=== kleinf/overtake/src/test/resources/field.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="factorType">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="idType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="colrowGrp">
		<xs:attribute name="factor" type="factorType" use="optional" default="1" />
		<xs:attribute name="offsetX" type="factorType" use="optional" default="0" />
		<xs:attribute name="offsetY" type="factorType" use="optional" default="0" />
	</xs:attributeGroup>
	<xs:complexType name="fieldType">
		<xs:sequence minOccurs="0" maxOccurs="1">
			<xs:element name="border" minOccurs="3" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="move">
							<xs:complexType>
								<xs:attribute name="x1" type="factorType" use="required" />
								<xs:attribute name="y1" type="factorType" use="required" />
							</xs:complexType>
						</xs:element>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="line">
								<xs:complexType>
									<xs:attribute name="x1" type="factorType" use="required" />
									<xs:attribute name="y1" type="factorType" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="quad">
								<xs:complexType>
									<xs:attribute name="x1" type="factorType" use="required" />
									<xs:attribute name="y1" type="factorType" use="required" />
									<xs:attribute name="x2" type="factorType" use="required" />
									<xs:attribute name="y2" type="factorType" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="curve">
								<xs:complexType>
									<xs:attribute name="x1" type="factorType" use="required" />
									<xs:attribute name="y1" type="factorType" use="required" />
									<xs:attribute name="x2" type="factorType" use="required" />
									<xs:attribute name="y2" type="factorType" use="required" />
									<xs:attribute name="x3" type="factorType" use="required" />
									<xs:attribute name="y3" type="factorType" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="idType" use="required" />
					<xs:attribute name="refBorderId" type="idType" use="required" />
					<xs:attribute name="refFieldX" type="xs:integer" use="required" />
					<xs:attribute name="refFieldY" type="xs:integer" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="colrowGrp" />
	</xs:complexType>
	<xs:element name="field">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="col">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="row" type="fieldType" maxOccurs="unbounded">
								<xs:key name="keyIdColRow">
									<xs:selector xpath="border" />
									<xs:field xpath="@id" />
								</xs:key>
								<xs:unique name="uniqueBorderRefColRow">
									<xs:selector xpath="border" />
									<xs:field xpath="@refBorderId" />
									<xs:field xpath="@refFieldX" />
									<xs:field xpath="@refFieldY" />
								</xs:unique>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="colrowGrp" />
					</xs:complexType>
				</xs:element>
				<xs:element name="row">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="col" type="fieldType" maxOccurs="unbounded">
								<xs:key name="keyIdRowCol">
									<xs:selector xpath="border" />
									<xs:field xpath="@id" />
								</xs:key>
								<xs:unique name="uniqueBorderRefRowCol">
									<xs:selector xpath="border" />
									<xs:field xpath="@refBorderId" />
									<xs:field xpath="@refFieldX" />
									<xs:field xpath="@refFieldY" />
								</xs:unique>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="colrowGrp" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kleinf/overtake/src/main/non-packaged-resources/Fields/Hex4.xml
<?xml version="1.0" encoding="UTF-8"?>
<field xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="field.xsd">
	<row factor="1.5">
		<col factor="0.5">
			<border id="1" refBorderId="4" refFieldX="-1" refFieldY="-1">
				<move x1="0" y1="0.25" />
				<line x1="0.5" y1="0" />
			</border>
			<border id="2" refBorderId="5" refFieldX="1" refFieldY="-1">
				<move x1="0.5" y1="0" />
				<line x1="1" y1="0.25" />
			</border>
			<border id="3" refBorderId="6" refFieldX="2" refFieldY="0">
				<move x1="1" y1="0.25" />
				<line x1="1" y1="0.75" />
			</border>
			<border id="4" refBorderId="1" refFieldX="1" refFieldY="0">
				<move x1="1" y1="0.75" />
				<line x1="0.5" y1="1" />
			</border>
			<border id="5" refBorderId="2" refFieldX="-1" refFieldY="0">
				<move x1="0.5" y1="1" />
				<line x1="0" y1="0.75" />
			</border>
			<border id="6" refBorderId="3" refFieldX="-2" refFieldY="0">
				<move x1="0" y1="0.75" />
				<line x1="0" y1="0.25" />
			</border>
		</col>
		<col factor="0.5" offsetY="0.75">
			<border id="1" refBorderId="4" refFieldX="-1" refFieldY="0">
				<move x1="0" y1="0.25" />
				<line x1="0.5" y1="0" />
			</border>
			<border id="2" refBorderId="5" refFieldX="1" refFieldY="0">
				<move x1="0.5" y1="0" />
				<line x1="1" y1="0.25" />
			</border>
			<border id="3" refBorderId="6" refFieldX="2" refFieldY="0">
				<move x1="1" y1="0.25" />
				<line x1="1" y1="0.75" />
			</border>
			<border id="4" refBorderId="1" refFieldX="1" refFieldY="1">
				<move x1="1" y1="0.75" />
				<line x1="0.5" y1="1" />
			</border>
			<border id="5" refBorderId="2" refFieldX="-1" refFieldY="1">
				<move x1="0.5" y1="1" />
				<line x1="0" y1="0.75" />
			</border>
			<border id="6" refBorderId="3" refFieldX="-2" refFieldY="0">
				<move x1="0" y1="0.75" />
				<line x1="0" y1="0.25" />
			</border>
		</col>
	</row>
</field>

=== kleinf/overtake/src/test/resources/A0.xml
<?xml version="1.0" encoding="UTF-8"?>
<field xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="field.xsd">
	<row factor="1">
		<col factor="1">
			<border id="1" refBorderId="4" refFieldX="0" refFieldY="-2">
				<move x1="0" y1="0" />
				<line x1="1" y1="0" />
			</border>
			<border id="2" refBorderId="4" refFieldX="1" refFieldY="0">
				<move x1="1" y1="0" />
				<line x1="1" y1="1" />
			</border>
			<border id="3" refBorderId="6" refFieldX="1" refFieldY="1">
				<move x1="1" y1="1" />
				<line x1="1" y1="2" />
			</border>
			<border id="4" refBorderId="1" refFieldX="0" refFieldY="2">
				<move x1="1" y1="2" />
				<line x1="0" y1="2" />
			</border>
			<border id="5" refBorderId="3" refFieldX="-2" refFieldY="1">
				<move x1="0" y1="2" />
				<line x1="0" y1="1" />
			</border>
			<border id="6" refBorderId="2" refFieldX="-1" refFieldY="0">
				<move x1="0" y1="1" />
				<line x1="0" y1="0" />
			</border>
		</col>
		<col factor="1">
			<border id="1" refBorderId="5" refFieldX="0" refFieldY="-1">
				<move x1="0" y1="0" />
				<line x1="1" y1="0" />
			</border>
			<border id="2" refBorderId="4" refFieldX="1" refFieldY="0">
				<move x1="1" y1="0" />
				<line x1="1" y1="1" />
			</border>
			<border id="3" refBorderId="1" refFieldX="0" refFieldY="1">
				<move x1="1" y1="1" />
				<line x1="0" y1="1" />
			</border>
			<border id="4" refBorderId="2" refFieldX="-1" refFieldY="0">
				<move x1="0" y1="1" />
				<line x1="0" y1="0" />
			</border>
		</col>
		<col factor="1">
			<border id="1" refBorderId="4" refFieldX="-1" refFieldY="-1">
				<move x1="0" y1="0" />
				<line x1="1" y1="0" />
			</border>
			<border id="2" refBorderId="6" refFieldX="1" refFieldY="0">
				<move x1="1" y1="0" />
				<line x1="1" y1="1" />
			</border>
			<border id="3" refBorderId="2" refFieldX="-1" refFieldY="1">
				<move x1="1" y1="1" />
				<line x1="0" y1="1" />
			</border>
			<border id="4" refBorderId="2" refFieldX="-1" refFieldY="0">
				<move x1="0" y1="1" />
				<line x1="0" y1="0" />
			</border>
		</col>
	</row>
	<row factor="1">
		<col factor="1" />
		<col factor="1">
			<border id="1" refBorderId="3" refFieldX="0" refFieldY="-1">
				<move x1="0" y1="0" />
				<line x1="1" y1="0" />
			</border>
			<border id="2" refBorderId="3" refFieldX="1" refFieldY="-1">
				<move x1="1" y1="0" />
				<line x1="2" y1="0" />
			</border>
			<border id="3" refBorderId="5" refFieldX="2" refFieldY="-1">
				<move x1="2" y1="0" />
				<line x1="2" y1="1" />
			</border>
			<border id="4" refBorderId="1" refFieldX="1" refFieldY="1">
				<move x1="2" y1="1" />
				<line x1="1" y1="1" />
			</border>
			<border id="5" refBorderId="1" refFieldX="0" refFieldY="1">
				<move x1="1" y1="1" />
				<line x1="0" y1="1" />
			</border>
			<border id="6" refBorderId="3" refFieldX="-1" refFieldY="-1">
				<move x1="0" y1="1" />
				<line x1="0" y1="0" />
			</border>
		</col>
		<col factor="1" />
	</row>
</field>
